language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  
# command to run tests
script: coverage unittest discover

#Command for coveralls
after_success:
  - coveralls
