name: tests

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install coveralls
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        pip install unittest
        python -m pytest --cov=./myapp --cov-report xml
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.xml

# name: Python package

# on: ["push", "pull_request"]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.9", "3.10"]

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install coveralls
#           pip install coverage
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       - name: Test with unittest
#         run: |
#           coverage run -m unittest discover
#           coveralls

#       - name: Coveralls
#         uses: coverallsapp/github-action@master
  
#   coveralls_finish:
#     needs: test
#     runs-on: ubuntu-latest
#       steps:
#     - name: Coveralls Finished
#       uses: coverallsapp/github-action@master
